name: 'Pull Request Size Labeler'
description: 'Automatically applies size labels to pull requests based on the total number of lines changed.'
author: 'Lukas Kuntze'

branding:
  icon: 'git-pull-request'
  color: 'orange'

inputs:
  github_api_url:
    description: 'Base URL of the GitHub API (used for GitHub Enterprise Server).'
    default: 'https://api.github.com'
    required: false

  github_token:
    description: 'GitHub token used for authenticating API requests.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
